In [1]:
queries = [
    # Easy: keyword-based
    {"id": 1, "query": "argan oil hair spray", "type": "keyword"},
    {"id": 2, "query": "volumizing dry shampoo", "type": "keyword"},
    {"id": 3, "query": "sulfate free shampoo", "type": "keyword"},

    # Medium: semantic
    {"id": 4, "query": "something to make frizzy hair smooth", "type": "semantic"},
    {"id": 5, "query": "product that protects hair from heat damage", "type": "semantic"},
    {"id": 6, "query": "gentle cleanser for sensitive scalp", "type": "semantic"},
    {"id": 7, "query": "natural scent that is not overpowering", "type": "semantic"},

    # Complex: require context, filtering, or reasoning
    {"id": 8, "query": "best leave-in conditioner for thick curly hair under $20", "type": "complex"},
    {"id": 9, "query": "what do people say about this product causing hair loss", "type": "complex"},
    {"id": 10, "query": "highly rated hair product that works for both men and women", "type": "complex"},
]

for q in queries:
    print(f"[{q['type'].upper():8}] {q['query']}")

[KEYWORD ] argan oil hair spray
[KEYWORD ] volumizing dry shampoo
[KEYWORD ] sulfate free shampoo
[SEMANTIC] something to make frizzy hair smooth
[SEMANTIC] product that protects hair from heat damage
[SEMANTIC] gentle cleanser for sensitive scalp
[SEMANTIC] natural scent that is not overpowering
[COMPLEX ] best leave-in conditioner for thick curly hair under $20
[COMPLEX ] what do people say about this product causing hair loss
[COMPLEX ] highly rated hair product that works for both men and women

In [11]:
#  BM25 
from rank_bm25 import BM25Okapi
import nltk
import pandas as pd
nltk.download('punkt')
from nltk.tokenize import word_tokenize
result = pd.read_parquet('../data/processed/merged.parquet')

# Build corpus: combine review title + text
corpus = (result['title'].fillna('') + ' ' + result['text'].fillna('')).tolist()
tokenized_corpus = [word_tokenize(doc.lower()) for doc in corpus]
bm25 = BM25Okapi(tokenized_corpus)

def bm25_search(query, top_k=5):
    tokens = word_tokenize(query.lower())
    scores = bm25.get_scores(tokens)
    top_indices = scores.argsort()[::-1][:top_k]
    return result.iloc[top_indices][['product_title', 'text', 'rating']].reset_index(drop=True)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\moham\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [16]:
from sentence_transformers import SentenceTransformer
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer('all-MiniLM-L6-v2')

# Load pre-computed embeddings instead of re-encoding
corpus_embeddings = np.load("../data/processed/embeddings.npy")

print(f"Embeddings shape: {corpus_embeddings.shape}")  # should be (num_docs, 384)

def semantic_search(query, top_k=5):
    query_embedding = model.encode([query])
    scores = cosine_similarity(query_embedding, corpus_embeddings)[0]
    top_indices = scores.argsort()[::-1][:top_k]
    return result.iloc[top_indices][['product_title','title', 'text', 'rating']].reset_index(drop=True)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Embeddings shape: (701528, 384)

In [ ]:
all_results = {}

for q in queries:
    qid = q['id']
    query_text = q['query']
    all_results[qid] = {
        "query": query_text,
        "type": q['type'],
        "bm25": bm25_search(query_text),
        "semantic": semantic_search(query_text)
    }
    print(f"Done: Q{qid} — {query_text}")

Done: Q1 — argan oil hair spray
Done: Q2 — volumizing dry shampoo
Done: Q3 — sulfate free shampoo
Done: Q4 — something to make frizzy hair smooth
Done: Q5 — product that protects hair from heat damage
Done: Q6 — gentle cleanser for sensitive scalp
Done: Q7 — natural scent that is not overpowering

In [ ]:
chosen = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # adjust to your chosen 5

for qid in chosen:
    q = all_results[qid]
    print(f"\n{'='*60}")
    print(f"Q{qid} [{q['type'].upper()}]: {q['query']}")
    print(f"\n--- BM25 Top 5 ---")
    display(q['bm25'])
    print(f"\n--- Semantic Top 5 ---")
    display(q['semantic'])

============================================================
Q1 [KEYWORD]: argan oil hair spray

--- BM25 Top 5 ---

,product_title,text,rating
0,"Nadira Organics Virgin Argan Oil for Skin, Fac...","Love this Argan oil, on my second bottle. Use ...",5.0
1,Savanaahs Organic Argan Oil 4 Oz / 120 ML 100%...,I love using Argan oil in my hair it is the pe...,4.0
2,Savanaahs Organic Argan Oil 4 Oz / 120 ML 100%...,I've been fooled by the 'Argan oil' label befo...,5.0
3,Livordo Moroccan Argan Oil Essential Organic C...,My daughter takes every Argan oil I get from m...,5.0
4,Savanaahs Organic Argan Oil 4 Oz / 120 ML 100%...,I love this oil. It is perfect. I used it on...,5.0

--- Semantic Top 5 ---

,product_title,text,rating
0,Cuticle Nippers,The cuticle nipper kept getting stuck. It does...,1.0
1,EcoBrow - All Natural Eyebrow Defining Wax (Pe...,"I'm in love, I received the Liz color as a sam...",5.0
2,New York Biology Vitamin C Serum for Face and ...,"Well, they weren't lying when they said it wor...",5.0
3,Compatible Oral-B Replacement Brush Heads - Va...,Easy Replacement and worked on other device I ...,5.0
4,WAVEBUILDER Seamless Durag- Black,I no longer have to worry about a line going d...,5.0

============================================================
Q2 [KEYWORD]: volumizing dry shampoo

--- BM25 Top 5 ---

,product_title,text,rating
0,TRESemmé Pro Pure Foam Shampoo For Volumized H...,Favorite volumizing shampoo ever!,5.0
1,"Batiste Volume Dry Shampoo, 6.73 Ounce (Pack o...","I've tried many, many (over a dozen) different...",5.0
2,EO Everyone Sulfate Free Nourish Shampoo and C...,Different shampoo was sent in this duo. I rece...,3.0
3,VEGAMOUR Vegalash Volumizing Mascara (Black/No...,LOVE your Vegalash Volumizing Mascara,5.0
4,Marc Anthony Instantly Thick Volumizing Condit...,Highly recommend the shampoo BUT the condition...,3.0

--- Semantic Top 5 ---

,product_title,text,rating
0,The Bare Pair King Kombo - Body Hair Managemen...,As you can probably tell by the title. This st...,5.0
1,Heel Moisturizing Socks - Codreamauto Moisturi...,These are very comfortable and go on easy. In ...,5.0
2,Hydrating Argan Oil Hair treatment Mask -Hair ...,smells like men cologne,1.0
3,"Lipsticks, Nude Coral Pink Matte lipsticks Lon...",I couldn’t wait to try because I really like t...,2.0
4,Clio Prism Air Eye Palette (#01 Coral Sparkle),I should have known better than to order an ey...,1.0

============================================================
Q3 [KEYWORD]: sulfate free shampoo

--- BM25 Top 5 ---

,product_title,text,rating
0,GK HAIR Global Keratin Moisturizing Shampoo an...,This is a great sulfate free shampoo and condi...,5.0
1,"Moroccan Argan Oil Shampoo, 8 Fl Oz - Smooths ...",My favorite sulfate free shampoo!,5.0
2,Argan Oil Shampoo and Conditioner Set - Sulfat...,"Good stuff, sulfate free. This shampoo and con...",4.0
3,"Moroccan Argan Oil Shampoo, 8 Fl Oz - Smooths ...",Wonderful sulfate free shampoo that actually l...,5.0
4,Marc Anthony Coconut Oil Shampoo 8.4 Ounce Tub...,Great repair or everyday shampoo. No sulphites...,5.0

--- Semantic Top 5 ---

,product_title,text,rating
0,"Chapfix Lip Balm for Men, SPF 15, with Beeswax...",I first saw these at Walmart. They charged 2 d...,5.0
1,"MEICOLY Fake Blood Washable,1.06oz Edible Stag...","I bought this because it said washable, smeare...",5.0
2,Braun 8000 360 Complete Foil/Cutter Block for ...,Tried chepo replacements but they r just not l...,5.0
3,ALICE False Eyelashes 3D Faux Mink Wispy Lashe...,Omg the worst lashes I've ever tried on amazon...,1.0
4,Ivation Portable Home Hair and Facial Steamer ...,"Like a previous reviewer, I also received stea...",4.0

============================================================
Q4 [SEMANTIC]: something to make frizzy hair smooth

--- BM25 Top 5 ---

,product_title,text,rating
0,Living Proof Full Shampoo,Makes my curly frizzy hair beautiful and smooth,5.0
1,Volumizing Deep Conditioning Hair Treatment - ...,MAKES HAIR FRIZZY SAMY GET CURLS AND BIOSILK S...,1.0
2,MONAT Junior Gentle Shampoo,My daughter has curly hair . I’ve tried other...,5.0
3,100% PURE ORGANIC Moroccan Argan Oil - For Fac...,It is helps frizzy hair and keep hair smooth ...,5.0
4,Hydrating Argan Oil Hair treatment Mask -Hair ...,Helped my dry frizzy hair. Leaves it smooth an...,5.0

--- Semantic Top 5 ---

,product_title,text,rating
0,Thinksport Safe Sunscreen SPF 50+ (6 ounce) (2...,Needed reef safe sunscreen for our upcoming tr...,5.0
1,Earfodo Clip in Bangs Human Hair Brown Bangs E...,Never even took it out of the bag. Totally not...,3.0
2,Vintage Mirror Comb Set - Makeup Vanity Table ...,The package arrived with only the mirror. Comb...,3.0
3,10 Pairs Natural Look Strong Magnetic Waterpro...,Great buy. Offers selection with diff styles. ...,4.0
4,Cosplay Dangan Ronpa Danganronpa Enoshima Junk...,"These are pretty basic, not super fancy and a ...",4.0

============================================================
Q5 [SEMANTIC]: product that protects hair from heat damage

--- BM25 Top 5 ---

,product_title,text,rating
0,"(KIDS FROZEN, FUCHSIA) lined HANDCRAFTED Rever...",My twin daughters like wearing that cap at nig...,5.0
1,CHI Flat Iron Stand,Perfect solution for House your flat iron and ...,5.0
2,Beyond The Zone Turn Up The Heat Protection Sp...,Use this product before I straighten or curl m...,5.0
3,"NEUMA Neumoisture Instant Fix, Kalette, Coconu...",it is the only product I now of that removes f...,5.0
4,DESIGNLINE Enchanted Midnight Leave-In Conditi...,This leave-in conditioner smells wonderful and...,5.0

--- Semantic Top 5 ---

,product_title,text,rating
0,Tik Tok Women Heatless Curling Rod Headband Fo...,Sooo easy to use.<br />The rod itself is nice ...,5.0
1,SantiGel Hand Sanitizer Gallon. 80% Ethyl Alco...,Does not smell that good. seems to work OK.,3.0
2,The Original Set of 3 Animal Print 100% Cotton...,"Love them, absorb well",5.0
3,"30PCS Diamond Nail Drill Bits Set, Carbide Dri...","I bought this for my daughter, for Christmas. ...",5.0
4,Atlas Semi Matte Texture Putty | Medium Shine ...,I have a full head of fine hair that needs pro...,5.0

============================================================
Q6 [SEMANTIC]: gentle cleanser for sensitive scalp

--- BM25 Top 5 ---

,product_title,text,rating
0,Charmzone Ginkgo Natural Cleansing Foam 180ml(...,I've been using this cleanser for many years n...,5.0
1,"Everyday Beauty Radiance Cleanser, Rejuvenatin...",[[VIDEOID:3396eaae81b5e0ac18c104bf8c1c08ab]] T...,5.0
2,"Face Cleaner by Whitney Jean, Gentle Facial Cl...",This is a great cleanser for sensitive skin! I...,5.0
3,AXIS-Y Quinoa One Step Balanced Gel Cleanser 6...,This is a very gentle cleanser. I have very se...,5.0
4,PHL Naturals Sensitive Skin Hydrating Facial C...,This is a very gentle cleanser that I love to ...,5.0

--- Semantic Top 5 ---

,product_title,text,rating
0,SH30 Replacement Heads for Philips Norelco Ser...,"I like the product, I have been with this raze...",5.0
1,Braun Silk Epil Female Epilator Se7921spa 1 Count,The best epilator I've ever used. Thx,5.0
2,THE MANE CHOICE - Crystal Orchid Biotin Infuse...,Can’t beat the price! In store you will pay ab...,4.0
3,"R-NEU 200 Cotton Rounds, 100% Natural Turkish ...",Poor quality! Falls apart easily. I have white...,1.0
4,Braun SE7281WD Xpressive Body System Rechargea...,I will first say that before you use this- do ...,5.0

============================================================
Q7 [SEMANTIC]: natural scent that is not overpowering

--- BM25 Top 5 ---

,product_title,text,rating
0,"WHIFF Introducing a Fragrance for all, YOU, by...",Nice clean scent that is not overpowering.,5.0
1,Every Man Jack Mens Sandalwood Body Wash for A...,Good soap. Nice scent but not overpowering,5.0
2,Plant Therapy Tiare Flower Whipped Shea Body B...,Good moisturizer with a lovely scent that is n...,5.0
3,Johnsons Baby Lotion 10.2 Ounce (300ml) (3 Pack),Scent was sickeningly strong and overpowering;...,1.0
4,Floral Street Wonderland Peony Eau De Parfum T...,"That it was lite, not overpowering.",5.0

--- Semantic Top 5 ---

,product_title,text,rating
0,Turquoise Drop Arm Harness Slave Chain Upper A...,I love. It was well worth the money.,5.0
1,Heyedrate Heated Eye Mask - Soothing Warm Comp...,They did help my burning itching eyes.,4.0
2,Donell AHA 20 Face and Body Care Exfoliating B...,Irritates your skin n causes rashes. don't wa...,1.0
3,Set of 6 BEAUTY TREATS Sugar Lip Scrub Tube,I'vee loved this product since I came across i...,5.0
4,55H+ Multi-Action Soap 7 oz. (Pack of 2),not good for my skin type,3.0

============================================================
Q8 [COMPLEX]: best leave-in conditioner for thick curly hair under $20

--- BM25 Top 5 ---

,product_title,text,rating
0,Roux Fermodyl Extra Strength Conditioner Vials,My hair is beautiful after using Fermodyl cond...,5.0
1,Marc Anthony Instantly Thick Volumizing Condit...,This conditioner actually works. The Marc Ant...,5.0
2,"Miss Jessie's Creme de la Creme, 8 Fl. Ounce","I love this conditioner, it is THE BEST for my...",5.0
3,L'Oreal Ever Curl Care System Hydracharge Leav...,This is the best product we’ve found to date f...,5.0
4,Lot of 10 Avon Moisture Therapy Intensive Heal...,Not only one of the best hand creams but also ...,5.0

--- Semantic Top 5 ---

,product_title,text,rating
0,Brazilian Body Wave Bundles With Closure Virgi...,This hair is absolutely beautiful! Texture is ...,5.0
1,Hylo-Care Eye Drops 10ml,Would really like to try the product but will ...,2.0
2,Silver Biotics Nano Silver Healing Lotion Crea...,Good product,5.0
3,"Mannequin Head,SMTSMT Male Styrofoam Mannequin...",Worked great for making my cheesecloth ghost f...,5.0
4,NYX Cosmetics Glam Shadow Stick - Set of 5,I like the color selections and easy applications,5.0

============================================================
Q9 [COMPLEX]: what do people say about this product causing hair loss

--- BM25 Top 5 ---

,product_title,text,rating
0,Living Proof Full Shampoo,Do your research. This product causes hair loss.,1.0
1,(2 Packs) Rice Water Hair Growth Treatment Sca...,"I had high hopes given the reviews, but it’s d...",1.0
2,Somang Korean Red Ginseng & Herbal Scalp Clean...,My girlfriend and her whole family uses this s...,5.0
3,i- Wen Sweet Almond Mint Cleansing Conditioner...,I just love this product I can't say enough go...,5.0
4,Tresemme Shampoo Botanique Curl Hydration 22 O...,"Couldn’t find at stores, so ordered thru Amazo...",5.0

--- Semantic Top 5 ---

,product_title,text,rating
0,"Fleece Ear Warmers Headband for Men & Women, T...",Made my face break out..,2.0
1,Mitchell's Wool Fat Shave Refill Soap,I purchased this shave soap based on the reput...,2.0
2,Salux Nylon Japanese Beauty Skin Bath Wash Clo...,I had a Korean body scrub in Los Angeles and f...,5.0
3,Moresoo 12 Inch Clip in Human Hair Extensions ...,Definitely will keep ordering from this seller...,5.0
4,Bath Scrubber Body Brush Shower Scrubber Back ...,"Loved the brush because of its softness, but t...",4.0

============================================================
Q10 [COMPLEX]: highly rated hair product that works for both men and women

--- BM25 Top 5 ---

,product_title,text,rating
0,JOOYHOOM Professional Hair Cutting Scissors Se...,Great price for a set of hair cutting kit! Wor...,5.0
1,SilkFeet NightCare Flexible Bladeless Exfoliat...,BEST BEST BEST foot care product,5.0
2,Baby Fresh Powder Perfume Scent - .33oz/10ml R...,The best thing I’ve ever smelled men and women...,5.0
3,Fearless Tape - Sensitive Skin - Women's Doubl...,Good for both men and women.,5.0
4,Cuba Quad 1 Gift Set (4 x 1.17 fl.oz. Eau De T...,Amazing combination of scents and flavors. Uni...,5.0

--- Semantic Top 5 ---

,product_title,text,rating
0,"Gel Toe Separators,XUZOU Toe Straighteners for...",They arrived very quickly and I used them righ...,5.0
1,Organic Activated Black Best Charcoal Natural ...,When you’re looking for a teeth whitener that’...,5.0
2,Healthcom Makeup Bags and Cases,This is a good buy. I'm not sure what to call ...,4.0
3,Francis,"Ok fragrance, but too floral for me. I would ...",3.0
4,Hot Spike Stud Blouse Shirts Collar Neck Tip B...,Cute fell in love with it but just took a long...,5.0